security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        public_api:
            pattern: ^/api/(login|logout|teacher/login|teacher/logout|admin/login|admin/logout)
            stateless: true
            security: false # Désactive l'authentification pour ces routes
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            jwt: ~
        main:
            lazy: true
            provider: app_user_provider
    access_control:
        - { path: ^/api/(login|logout|teacher/login|teacher/logout|admin/login|admin/logout), roles: PUBLIC_ACCESS }
        - { path: ^/api/teacher, roles: ROLE_PROFESSEUR }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10