# config/services.yaml
parameters:
    bibliotheque_directory: '%kernel.project_dir%/public/uploads/bibliotheque'
    temp_directory: '%kernel.project_dir%/public/uploads/temp'
    supports_upload_dir: '%kernel.project_dir%/public/uploads/supports'
    uploads_directory: '%kernel.project_dir%/public/uploads'
    app.base_url: 'http://localhost:8000'
    supports_directory: '%kernel.project_dir%/public/uploads/supports'
    google_gemini_api_key: '%env(GOOGLE_GEMINI_API_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\GeminiService:
        arguments:
            $geminiApiKey: '%google_gemini_api_key%'
            $logger: '@monolog.logger'
            $httpClient: '@http_client'